/* 
  This file was generated automatically with ../../scripts/maple2c.pl.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2018 (X86 64 LINUX)
  Maple source      : lda_x_erf_jt.mpl
  Type of functional: lda_exc
*/

#define maple2c_order 4
#define MAPLE2C_FLAGS (XC_FLAGS_I_HAVE_EXC | XC_FLAGS_I_HAVE_VXC | XC_FLAGS_I_HAVE_FXC | XC_FLAGS_I_HAVE_KXC | XC_FLAGS_I_HAVE_LXC)


static inline void
func_unpol(const xc_func_type *p, int order, const double *rho, double *zk, LDA_OUT_PARAMS_NO_EXC(double *))
{

#ifndef XC_DONT_COMPILE_EXC
  double t1, t3, t4, t5, t6, t7, t8, t9;
  double t10, t12;

#ifndef XC_DONT_COMPILE_FXC
  double t15;

#ifndef XC_DONT_COMPILE_LXC
  double t24;
#endif

#endif

#endif



  t1 = M_CBRT3;
  t3 = POW_1_3(0.1e1 / M_PI);
  t4 = t1 * t3;
  t5 = M_CBRT4;
  t6 = t5 * t5;
  t7 = M_CBRT2;
  t8 = t7 * t7;
  t9 = t6 * t8;
  t10 = POW_1_3(rho[0]);
  t12 = t4 * t9 * t10;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = -0.3e1 / 0.16e2 * t12;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = -t12 / 0.4e1;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t15 = t10 * t10;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = -t4 * t9 / t15 / 0.12e2;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = t4 * t9 / t15 / rho[0] / 0.18e2;

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


  t24 = rho[0] * rho[0];
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[0] = -0.5e1 / 0.54e2 * t4 * t9 / t15 / t24;

#ifndef XC_DONT_COMPILE_MXC

  if(order < 5) return;


#endif

#endif

#endif

#endif

#endif


}


static inline void
func_ferr(const xc_func_type *p, int order, const double *rho, double *zk, LDA_OUT_PARAMS_NO_EXC(double *))
{

#ifndef XC_DONT_COMPILE_EXC
  double t1, t3, t4, t5, t6, t7, t9;

#ifndef XC_DONT_COMPILE_FXC
  double t12;

#ifndef XC_DONT_COMPILE_LXC
  double t21;
#endif

#endif

#endif



  t1 = M_CBRT3;
  t3 = POW_1_3(0.1e1 / M_PI);
  t4 = t1 * t3;
  t5 = M_CBRT4;
  t6 = t5 * t5;
  t7 = POW_1_3(rho[0]);
  t9 = t4 * t6 * t7;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = -0.3e1 / 0.8e1 * t9;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = -t9 / 0.2e1;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t12 = t7 * t7;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = -t4 * t6 / t12 / 0.6e1;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = t4 * t6 / t12 / rho[0] / 0.9e1;

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


  t21 = rho[0] * rho[0];
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[0] = -0.5e1 / 0.27e2 * t4 * t6 / t12 / t21;

#ifndef XC_DONT_COMPILE_MXC

  if(order < 5) return;


#endif

#endif

#endif

#endif

#endif


}


static inline void
func_pol(const xc_func_type *p, int order, const double *rho, double *zk, LDA_OUT_PARAMS_NO_EXC(double *))
{

#ifndef XC_DONT_COMPILE_EXC
  double t1, t3, t5, t6, t7, t8, t9, t10;
  double t11, t12, t13, t14, t15, t17, t18, t21;
  double t22, t24;

#ifndef XC_DONT_COMPILE_VXC
  double t26, t29, t30, t31, t32, t33, t34, t36;
  double t39, t43, t45, t49;

#ifndef XC_DONT_COMPILE_FXC
  double t52, t54, t56, t57, t60, t61, t62, t63;
  double t67, t68, t70, t73, t74, t75, t78, t81;
  double t87, t88, t90, t93, t96, t99, t103, t107;
  double t111, t114, t117, t121;

#ifndef XC_DONT_COMPILE_KXC
  double t124, t126, t129, t132, t135, t137, t138, t141;
  double t144, t145, t146, t148, t152, t153, t156, t159;
  double t162, t169, t170, t173, t174, t177, t187, t190;
  double t201, t206, t208, t213, t218, t221, t226, t229;
  double t233, t238, t244, t247, t252, t256;

#ifndef XC_DONT_COMPILE_LXC
  double t261, t264, t267, t273, t274, t276, t277, t283;
  double t289, t290, t292, t295, t297, t298, t304, t321;
  double t323, t324, t325, t350, t368, t377, t386, t388;
  double t399, t402, t441, t449, t469, t491, t498, t503;
  double t509, t512, t517;
#endif

#endif

#endif

#endif

#endif



  t1 = M_CBRT3;
  t3 = POW_1_3(0.1e1 / M_PI);
  t5 = M_CBRT4;
  t6 = t5 * t5;
  t7 = t1 * t3 * t6;
  t8 = M_CBRT2;
  t9 = t8 * t8;
  t10 = rho[0] - rho[1];
  t11 = rho[0] + rho[1];
  t12 = 0.1e1 / t11;
  t13 = t10 * t12;
  t14 = 0.1e1 + t13;
  t15 = POW_1_3(t14);
  t17 = 0.1e1 - t13;
  t18 = POW_1_3(t17);
  t21 = t9 * (t15 * t14 + t18 * t17);
  t22 = POW_1_3(t11);
  t24 = t7 * t21 * t22;
  if(zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    zk[0] = -0.3e1 / 0.32e2 * t24;

#ifndef XC_DONT_COMPILE_VXC

  if(order < 1) return;


  t26 = t24 / 0.8e1;
  t29 = t22 * t11 * t1 * t3;
  t30 = t6 * t9;
  t31 = t11 * t11;
  t32 = 0.1e1 / t31;
  t33 = t10 * t32;
  t34 = t12 - t33;
  t36 = -t34;
  t39 = 0.4e1 / 0.3e1 * t15 * t34 + 0.4e1 / 0.3e1 * t18 * t36;
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[0] = -t26 - 0.3e1 / 0.32e2 * t29 * t30 * t39;

  t43 = -t12 - t33;
  t45 = -t43;
  t49 = t30 * (0.4e1 / 0.3e1 * t15 * t43 + 0.4e1 / 0.3e1 * t18 * t45);
  if(vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    vrho[1] = -t26 - 0.3e1 / 0.32e2 * t29 * t49;

#ifndef XC_DONT_COMPILE_FXC

  if(order < 2) return;


  t52 = t9 * t39;
  t54 = t7 * t52 * t22;
  t56 = t22 * t22;
  t57 = 0.1e1 / t56;
  t60 = t7 * t21 * t57 / 0.24e2;
  t61 = t15 * t15;
  t62 = 0.1e1 / t61;
  t63 = t34 * t34;
  t67 = 0.1e1 / t31 / t11;
  t68 = t10 * t67;
  t70 = -0.2e1 * t32 + 0.2e1 * t68;
  t73 = t18 * t18;
  t74 = 0.1e1 / t73;
  t75 = t36 * t36;
  t78 = -t70;
  t81 = 0.4e1 / 0.9e1 * t62 * t63 + 0.4e1 / 0.3e1 * t15 * t70 + 0.4e1 / 0.9e1 * t74 * t75 + 0.4e1 / 0.3e1 * t18 * t78;
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[0] = -t54 / 0.4e1 - t60 - 0.3e1 / 0.32e2 * t29 * t30 * t81;

  t87 = t22 * t1 * t3;
  t88 = t87 * t49;
  t90 = t62 * t43;
  t93 = t15 * t10;
  t96 = t74 * t45;
  t99 = t18 * t10;
  t103 = t30 * (0.4e1 / 0.9e1 * t90 * t34 + 0.8e1 / 0.3e1 * t93 * t67 + 0.4e1 / 0.9e1 * t96 * t36 - 0.8e1 / 0.3e1 * t99 * t67);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[1] = -t54 / 0.8e1 - t60 - t88 / 0.8e1 - 0.3e1 / 0.32e2 * t29 * t103;

  t107 = t43 * t43;
  t111 = 0.2e1 * t32 + 0.2e1 * t68;
  t114 = t45 * t45;
  t117 = -t111;
  t121 = t30 * (0.4e1 / 0.9e1 * t62 * t107 + 0.4e1 / 0.3e1 * t15 * t111 + 0.4e1 / 0.9e1 * t74 * t114 + 0.4e1 / 0.3e1 * t18 * t117);
  if(v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    v2rho2[2] = -t88 / 0.4e1 - t60 - 0.3e1 / 0.32e2 * t29 * t121;

#ifndef XC_DONT_COMPILE_KXC

  if(order < 3) return;


  t124 = t9 * t81;
  t126 = t7 * t124 * t22;
  t129 = t7 * t52 * t57;
  t132 = 0.1e1 / t56 / t11;
  t135 = t7 * t21 * t132 / 0.36e2;
  t137 = 0.1e1 / t61 / t14;
  t138 = t63 * t34;
  t141 = t62 * t34;
  t144 = t31 * t31;
  t145 = 0.1e1 / t144;
  t146 = t10 * t145;
  t148 = 0.6e1 * t67 - 0.6e1 * t146;
  t152 = 0.1e1 / t73 / t17;
  t153 = t75 * t36;
  t156 = t74 * t36;
  t159 = -t148;
  t162 = -0.8e1 / 0.27e2 * t137 * t138 + 0.4e1 / 0.3e1 * t141 * t70 + 0.4e1 / 0.3e1 * t15 * t148 - 0.8e1 / 0.27e2 * t152 * t153 + 0.4e1 / 0.3e1 * t156 * t78 + 0.4e1 / 0.3e1 * t18 * t159;
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[0] = -0.3e1 / 0.8e1 * t126 - t129 / 0.8e1 + t135 - 0.3e1 / 0.32e2 * t29 * t30 * t162;

  t169 = t57 * t1 * t3;
  t170 = t169 * t49;
  t173 = t87 * t103 / 0.4e1;
  t174 = t137 * t43;
  t177 = t62 * t10;
  t187 = t152 * t45;
  t190 = t74 * t10;
  t201 = t30 * (-0.8e1 / 0.27e2 * t174 * t63 + 0.16e2 / 0.9e1 * t177 * t67 * t34 + 0.4e1 / 0.9e1 * t90 * t70 + 0.8e1 / 0.3e1 * t15 * t67 - 0.8e1 * t93 * t145 - 0.8e1 / 0.27e2 * t187 * t75 - 0.16e2 / 0.9e1 * t190 * t67 * t36 + 0.4e1 / 0.9e1 * t96 * t78 - 0.8e1 / 0.3e1 * t18 * t67 + 0.8e1 * t99 * t145);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[1] = -t126 / 0.8e1 - t129 / 0.12e2 + t135 - t170 / 0.24e2 - t173 - 0.3e1 / 0.32e2 * t29 * t201;

  t206 = t87 * t121;
  t208 = t137 * t107;
  t213 = t62 * t111;
  t218 = -0.2e1 * t67 - 0.6e1 * t146;
  t221 = t152 * t114;
  t226 = t74 * t117;
  t229 = -t218;
  t233 = t30 * (-0.8e1 / 0.27e2 * t208 * t34 + 0.16e2 / 0.9e1 * t90 * t68 + 0.4e1 / 0.9e1 * t213 * t34 + 0.4e1 / 0.3e1 * t15 * t218 - 0.8e1 / 0.27e2 * t221 * t36 - 0.16e2 / 0.9e1 * t96 * t68 + 0.4e1 / 0.9e1 * t226 * t36 + 0.4e1 / 0.3e1 * t18 * t229);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[2] = -t170 / 0.12e2 - t173 - t129 / 0.24e2 + t135 - t206 / 0.8e1 - 0.3e1 / 0.32e2 * t29 * t233;

  t238 = t107 * t43;
  t244 = -0.6e1 * t67 - 0.6e1 * t146;
  t247 = t114 * t45;
  t252 = -t244;
  t256 = t30 * (-0.8e1 / 0.27e2 * t137 * t238 + 0.4e1 / 0.3e1 * t90 * t111 + 0.4e1 / 0.3e1 * t15 * t244 - 0.8e1 / 0.27e2 * t152 * t247 + 0.4e1 / 0.3e1 * t96 * t117 + 0.4e1 / 0.3e1 * t18 * t252);
  if(v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    v3rho3[3] = -t170 / 0.8e1 - 0.3e1 / 0.8e1 * t206 + t135 - 0.3e1 / 0.32e2 * t29 * t256;

#ifndef XC_DONT_COMPILE_LXC

  if(order < 4) return;


  t261 = t7 * t9 * t162 * t22;
  t264 = t7 * t124 * t57;
  t267 = t7 * t52 * t132;
  t273 = 0.5e1 / 0.108e3 * t7 * t21 / t56 / t31;
  t274 = t14 * t14;
  t276 = 0.1e1 / t61 / t274;
  t277 = t63 * t63;
  t283 = t70 * t70;
  t289 = 0.1e1 / t144 / t11;
  t290 = t10 * t289;
  t292 = -0.24e2 * t145 + 0.24e2 * t290;
  t295 = t17 * t17;
  t297 = 0.1e1 / t73 / t295;
  t298 = t75 * t75;
  t304 = t78 * t78;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[0] = -t261 / 0.2e1 - t264 / 0.4e1 + t267 / 0.9e1 - t273 - 0.3e1 / 0.32e2 * t29 * t30 * (0.40e2 / 0.81e2 * t276 * t277 - 0.16e2 / 0.9e1 * t137 * t63 * t70 + 0.4e1 / 0.3e1 * t62 * t283 + 0.16e2 / 0.9e1 * t141 * t148 + 0.4e1 / 0.3e1 * t15 * t292 + 0.40e2 / 0.81e2 * t297 * t298 - 0.16e2 / 0.9e1 * t152 * t75 * t78 + 0.4e1 / 0.3e1 * t74 * t304 + 0.16e2 / 0.9e1 * t156 * t159 - 0.4e1 / 0.3e1 * t18 * t292);

  t321 = t132 * t1 * t3 * t49;
  t323 = t169 * t103;
  t324 = t323 / 0.8e1;
  t325 = t87 * t201;
  t350 = 0.32e2 * t93 * t289;
  t368 = 0.32e2 * t99 * t289;
  t377 = -0.8e1 * t177 * t145 * t34 + 0.8e1 * t190 * t145 * t36 + 0.40e2 / 0.81e2 * t276 * t43 * t138 - 0.8e1 / 0.9e1 * t174 * t34 * t70 - 0.16e2 / 0.9e1 * t137 * t10 * t67 * t63 + 0.8e1 / 0.3e1 * t62 * t67 * t34 + 0.8e1 / 0.3e1 * t177 * t67 * t70 + t350 + 0.40e2 / 0.81e2 * t297 * t45 * t153 - 0.8e1 / 0.9e1 * t187 * t36 * t78 + 0.16e2 / 0.9e1 * t152 * t10 * t67 * t75 - 0.8e1 / 0.3e1 * t74 * t67 * t36 - 0.8e1 / 0.3e1 * t190 * t67 * t78 - t368 + 0.4e1 / 0.9e1 * t90 * t148 - 0.16e2 * t15 * t145 + 0.4e1 / 0.9e1 * t96 * t159 + 0.16e2 * t18 * t145;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[1] = -t261 / 0.8e1 - t264 / 0.8e1 + t267 / 0.12e2 - t273 + t321 / 0.36e2 - t324 - 0.3e1 / 0.8e1 * t325 - 0.3e1 / 0.32e2 * t29 * t30 * t377;

  t386 = t169 * t121;
  t388 = t87 * t233;
  t399 = t10 * t10;
  t402 = 0.1e1 / t144 / t31;
  t441 = 0.40e2 / 0.81e2 * t276 * t107 * t63 - 0.64e2 / 0.27e2 * t174 * t34 * t10 * t67 - 0.8e1 / 0.27e2 * t208 * t70 + 0.32e2 / 0.9e1 * t62 * t399 * t402 + 0.16e2 / 0.9e1 * t90 * t67 - 0.16e2 / 0.3e1 * t90 * t146 - 0.8e1 / 0.27e2 * t137 * t111 * t63 + 0.8e1 / 0.9e1 * t62 * t218 * t34 + 0.4e1 / 0.9e1 * t213 * t70 + t350 + 0.40e2 / 0.81e2 * t297 * t114 * t75 + 0.64e2 / 0.27e2 * t187 * t36 * t10 * t67 - 0.8e1 / 0.27e2 * t221 * t78 + 0.32e2 / 0.9e1 * t74 * t399 * t402 - 0.16e2 / 0.9e1 * t96 * t67 + 0.16e2 / 0.3e1 * t96 * t146 - 0.8e1 / 0.27e2 * t152 * t117 * t75 + 0.8e1 / 0.9e1 * t74 * t229 * t36 + 0.4e1 / 0.9e1 * t226 * t78 - t368;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[2] = t321 / 0.18e2 - t323 / 0.6e1 - t325 / 0.4e1 - t264 / 0.24e2 + t267 / 0.18e2 - t273 - t386 / 0.24e2 - t388 / 0.4e1 - 0.3e1 / 0.32e2 * t29 * t30 * t441;

  t449 = t87 * t256;
  t469 = 0.12e2 * t145 + 0.24e2 * t290;
  t491 = 0.40e2 / 0.81e2 * t276 * t238 * t34 - 0.16e2 / 0.9e1 * t208 * t68 - 0.8e1 / 0.9e1 * t174 * t111 * t34 + 0.8e1 / 0.3e1 * t177 * t67 * t111 + 0.4e1 / 0.3e1 * t90 * t218 + 0.4e1 / 0.9e1 * t62 * t244 * t34 + 0.4e1 / 0.3e1 * t15 * t469 + 0.40e2 / 0.81e2 * t297 * t247 * t36 + 0.16e2 / 0.9e1 * t221 * t68 - 0.8e1 / 0.9e1 * t187 * t117 * t36 - 0.8e1 / 0.3e1 * t190 * t67 * t117 + 0.4e1 / 0.3e1 * t96 * t229 + 0.4e1 / 0.9e1 * t74 * t252 * t36 - 0.4e1 / 0.3e1 * t18 * t469;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[3] = t321 / 0.12e2 - t324 - t386 / 0.8e1 - 0.3e1 / 0.8e1 * t388 + t267 / 0.36e2 - t273 - t449 / 0.8e1 - 0.3e1 / 0.32e2 * t29 * t30 * t491;

  t498 = t107 * t107;
  t503 = t111 * t111;
  t509 = 0.24e2 * t145 + 0.24e2 * t290;
  t512 = t114 * t114;
  t517 = t117 * t117;
  if(v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    v4rho4[4] = t321 / 0.9e1 - t386 / 0.4e1 - t449 / 0.2e1 - t273 - 0.3e1 / 0.32e2 * t29 * t30 * (0.40e2 / 0.81e2 * t276 * t498 - 0.16e2 / 0.9e1 * t208 * t111 + 0.4e1 / 0.3e1 * t62 * t503 + 0.16e2 / 0.9e1 * t90 * t244 + 0.4e1 / 0.3e1 * t15 * t509 + 0.40e2 / 0.81e2 * t297 * t512 - 0.16e2 / 0.9e1 * t221 * t117 + 0.4e1 / 0.3e1 * t74 * t517 + 0.16e2 / 0.9e1 * t96 * t252 - 0.4e1 / 0.3e1 * t18 * t509);

#ifndef XC_DONT_COMPILE_MXC

  if(order < 5) return;


#endif

#endif

#endif

#endif

#endif


}

