/*
  This file was generated automatically with ../../scripts/maple2c.py.
  Do not edit this file directly as it can be overwritten!!

  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.

  Maple version     : Maple 2021 (X86 64 LINUX)
  Maple source      : lda_x_erf_jt.mpl
  Type of functional: lda_exc
*/

#define maple2c_order 4
#define MAPLE2C_FLAGS (XC_FLAGS_I_HAVE_EXC | XC_FLAGS_I_HAVE_VXC | XC_FLAGS_I_HAVE_FXC | XC_FLAGS_I_HAVE_KXC | XC_FLAGS_I_HAVE_LXC)


#ifndef XC_DONT_COMPILE_EXC
GPU_DEVICE_FUNCTION static inline void
func_exc_unpol(const xc_func_type *p, size_t ip, const double *rho, xc_lda_out_params *out)
{
  double t2, t3, t4, t6, t8, t10, t11, t15;
  double tzk0;


  t2 = rho[0] / 0.2e1 <= p->dens_threshold;
  t3 = M_CBRT3;
  t4 = M_CBRTPI;
  t6 = t3 / t4;
  t8 = POW_1_3(p->zeta_threshold);
  t10 = my_piecewise3(0.1e1 <= p->zeta_threshold, t8 * p->zeta_threshold, 1);
  t11 = POW_1_3(rho[0]);
  t15 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t6 * t10 * t11);
  tzk0 = 0.2e1 * t15;

  if(out->zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    out->zk[ip*p->dim.zk + 0] += tzk0;

}

#endif


#ifndef XC_DONT_COMPILE_VXC
GPU_DEVICE_FUNCTION static inline void
func_vxc_unpol(const xc_func_type *p, size_t ip, const double *rho, xc_lda_out_params *out)
{
  double t2, t3, t4, t6, t8, t10, t11, t15;
  double tzk0;

  double t16, t21, tvrho0;


  t2 = rho[0] / 0.2e1 <= p->dens_threshold;
  t3 = M_CBRT3;
  t4 = M_CBRTPI;
  t6 = t3 / t4;
  t8 = POW_1_3(p->zeta_threshold);
  t10 = my_piecewise3(0.1e1 <= p->zeta_threshold, t8 * p->zeta_threshold, 1);
  t11 = POW_1_3(rho[0]);
  t15 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t6 * t10 * t11);
  tzk0 = 0.2e1 * t15;

  if(out->zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    out->zk[ip*p->dim.zk + 0] += tzk0;

  t16 = t11 * t11;
  t21 = my_piecewise3(t2, 0, -t6 * t10 / t16 / 0.8e1);
  tvrho0 = 0.2e1 * rho[0] * t21 + 0.2e1 * t15;

  if(out->vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    out->vrho[ip*p->dim.vrho + 0] += tvrho0;

}

#endif


#ifndef XC_DONT_COMPILE_FXC
GPU_DEVICE_FUNCTION static inline void
func_fxc_unpol(const xc_func_type *p, size_t ip, const double *rho, xc_lda_out_params *out)
{
  double t2, t3, t4, t6, t8, t10, t11, t15;
  double tzk0;

  double t16, t21, tvrho0;

  double t30, tv2rho20;


  t2 = rho[0] / 0.2e1 <= p->dens_threshold;
  t3 = M_CBRT3;
  t4 = M_CBRTPI;
  t6 = t3 / t4;
  t8 = POW_1_3(p->zeta_threshold);
  t10 = my_piecewise3(0.1e1 <= p->zeta_threshold, t8 * p->zeta_threshold, 1);
  t11 = POW_1_3(rho[0]);
  t15 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t6 * t10 * t11);
  tzk0 = 0.2e1 * t15;

  if(out->zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    out->zk[ip*p->dim.zk + 0] += tzk0;

  t16 = t11 * t11;
  t21 = my_piecewise3(t2, 0, -t6 * t10 / t16 / 0.8e1);
  tvrho0 = 0.2e1 * rho[0] * t21 + 0.2e1 * t15;

  if(out->vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    out->vrho[ip*p->dim.vrho + 0] += tvrho0;

  t30 = my_piecewise3(t2, 0, t6 * t10 / t16 / rho[0] / 0.12e2);
  tv2rho20 = 0.2e1 * rho[0] * t30 + 0.4e1 * t21;

  if(out->v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    out->v2rho2[ip*p->dim.v2rho2 + 0] += tv2rho20;

}

#endif


#ifndef XC_DONT_COMPILE_KXC
GPU_DEVICE_FUNCTION static inline void
func_kxc_unpol(const xc_func_type *p, size_t ip, const double *rho, xc_lda_out_params *out)
{
  double t2, t3, t4, t6, t8, t10, t11, t15;
  double tzk0;

  double t16, t21, tvrho0;

  double t30, tv2rho20;

  double t34, t40, tv3rho30;


  t2 = rho[0] / 0.2e1 <= p->dens_threshold;
  t3 = M_CBRT3;
  t4 = M_CBRTPI;
  t6 = t3 / t4;
  t8 = POW_1_3(p->zeta_threshold);
  t10 = my_piecewise3(0.1e1 <= p->zeta_threshold, t8 * p->zeta_threshold, 1);
  t11 = POW_1_3(rho[0]);
  t15 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t6 * t10 * t11);
  tzk0 = 0.2e1 * t15;

  if(out->zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    out->zk[ip*p->dim.zk + 0] += tzk0;

  t16 = t11 * t11;
  t21 = my_piecewise3(t2, 0, -t6 * t10 / t16 / 0.8e1);
  tvrho0 = 0.2e1 * rho[0] * t21 + 0.2e1 * t15;

  if(out->vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    out->vrho[ip*p->dim.vrho + 0] += tvrho0;

  t30 = my_piecewise3(t2, 0, t6 * t10 / t16 / rho[0] / 0.12e2);
  tv2rho20 = 0.2e1 * rho[0] * t30 + 0.4e1 * t21;

  if(out->v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    out->v2rho2[ip*p->dim.v2rho2 + 0] += tv2rho20;

  t34 = rho[0] * rho[0];
  t40 = my_piecewise3(t2, 0, -0.5e1 / 0.36e2 * t6 * t10 / t16 / t34);
  tv3rho30 = 0.2e1 * rho[0] * t40 + 0.6e1 * t30;

  if(out->v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    out->v3rho3[ip*p->dim.v3rho3 + 0] += tv3rho30;

}

#endif


#ifndef XC_DONT_COMPILE_LXC
GPU_DEVICE_FUNCTION static inline void
func_lxc_unpol(const xc_func_type *p, size_t ip, const double *rho, xc_lda_out_params *out)
{
  double t2, t3, t4, t6, t8, t10, t11, t15;
  double tzk0;

  double t16, t21, tvrho0;

  double t30, tv2rho20;

  double t34, t40, tv3rho30;

  double t50, tv4rho40;


  t2 = rho[0] / 0.2e1 <= p->dens_threshold;
  t3 = M_CBRT3;
  t4 = M_CBRTPI;
  t6 = t3 / t4;
  t8 = POW_1_3(p->zeta_threshold);
  t10 = my_piecewise3(0.1e1 <= p->zeta_threshold, t8 * p->zeta_threshold, 1);
  t11 = POW_1_3(rho[0]);
  t15 = my_piecewise3(t2, 0, -0.3e1 / 0.8e1 * t6 * t10 * t11);
  tzk0 = 0.2e1 * t15;

  if(out->zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    out->zk[ip*p->dim.zk + 0] += tzk0;

  t16 = t11 * t11;
  t21 = my_piecewise3(t2, 0, -t6 * t10 / t16 / 0.8e1);
  tvrho0 = 0.2e1 * rho[0] * t21 + 0.2e1 * t15;

  if(out->vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    out->vrho[ip*p->dim.vrho + 0] += tvrho0;

  t30 = my_piecewise3(t2, 0, t6 * t10 / t16 / rho[0] / 0.12e2);
  tv2rho20 = 0.2e1 * rho[0] * t30 + 0.4e1 * t21;

  if(out->v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    out->v2rho2[ip*p->dim.v2rho2 + 0] += tv2rho20;

  t34 = rho[0] * rho[0];
  t40 = my_piecewise3(t2, 0, -0.5e1 / 0.36e2 * t6 * t10 / t16 / t34);
  tv3rho30 = 0.2e1 * rho[0] * t40 + 0.6e1 * t30;

  if(out->v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    out->v3rho3[ip*p->dim.v3rho3 + 0] += tv3rho30;

  t50 = my_piecewise3(t2, 0, 0.1e2 / 0.27e2 * t6 * t10 / t16 / t34 / rho[0]);
  tv4rho40 = 0.2e1 * rho[0] * t50 + 0.8e1 * t40;

  if(out->v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    out->v4rho4[ip*p->dim.v4rho4 + 0] += tv4rho40;

}

#endif


#ifndef XC_DONT_COMPILE_EXC
GPU_DEVICE_FUNCTION static inline void
func_exc_pol(const xc_func_type *p, size_t ip, const double *rho, xc_lda_out_params *out)
{
  double t1, t2, t3, t5, t6, t7, t8, t10;
  double t11, t12, t13, t14, t15, t19, t20, t24;
  double t25, t26, t28, t29, t30, t34, t38, tzk0;


  t1 = rho[0] <= p->dens_threshold;
  t2 = M_CBRT3;
  t3 = M_CBRTPI;
  t5 = t2 / t3;
  t6 = rho[0] + rho[1];
  t7 = 0.1e1 / t6;
  t8 = rho[0] * t7;
  t10 = 0.2e1 * t8 <= p->zeta_threshold;
  t11 = POW_1_3(p->zeta_threshold);
  t12 = t11 * p->zeta_threshold;
  t13 = M_CBRT2;
  t14 = t13 * rho[0];
  t15 = POW_1_3(t8);
  t19 = my_piecewise3(t10, t12, 0.2e1 * t14 * t7 * t15);
  t20 = POW_1_3(t6);
  t24 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t19 * t20);
  t25 = rho[1] <= p->dens_threshold;
  t26 = rho[1] * t7;
  t28 = 0.2e1 * t26 <= p->zeta_threshold;
  t29 = t13 * rho[1];
  t30 = POW_1_3(t26);
  t34 = my_piecewise3(t28, t12, 0.2e1 * t29 * t7 * t30);
  t38 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t34 * t20);
  tzk0 = t24 + t38;

  if(out->zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    out->zk[ip*p->dim.zk + 0] += tzk0;

}

#endif


#ifndef XC_DONT_COMPILE_VXC
GPU_DEVICE_FUNCTION static inline void
func_vxc_pol(const xc_func_type *p, size_t ip, const double *rho, xc_lda_out_params *out)
{
  double t1, t2, t3, t5, t6, t7, t8, t10;
  double t11, t12, t13, t14, t15, t19, t20, t24;
  double t25, t26, t28, t29, t30, t34, t38, tzk0;

  double t39, t42, t43, t46, t47, t48, t49, t51;
  double t56, t60, t61, t64, t66, t69, t70, t71;
  double t72, t73, t74, t75, t76, t80, t86, t88;
  double tvrho0, t91, t92, t93, t97, t102, t105, t107;
  double t112, t117, tvrho1;


  t1 = rho[0] <= p->dens_threshold;
  t2 = M_CBRT3;
  t3 = M_CBRTPI;
  t5 = t2 / t3;
  t6 = rho[0] + rho[1];
  t7 = 0.1e1 / t6;
  t8 = rho[0] * t7;
  t10 = 0.2e1 * t8 <= p->zeta_threshold;
  t11 = POW_1_3(p->zeta_threshold);
  t12 = t11 * p->zeta_threshold;
  t13 = M_CBRT2;
  t14 = t13 * rho[0];
  t15 = POW_1_3(t8);
  t19 = my_piecewise3(t10, t12, 0.2e1 * t14 * t7 * t15);
  t20 = POW_1_3(t6);
  t24 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t19 * t20);
  t25 = rho[1] <= p->dens_threshold;
  t26 = rho[1] * t7;
  t28 = 0.2e1 * t26 <= p->zeta_threshold;
  t29 = t13 * rho[1];
  t30 = POW_1_3(t26);
  t34 = my_piecewise3(t28, t12, 0.2e1 * t29 * t7 * t30);
  t38 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t34 * t20);
  tzk0 = t24 + t38;

  if(out->zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    out->zk[ip*p->dim.zk + 0] += tzk0;

  t39 = t13 * t7;
  t42 = t6 * t6;
  t43 = 0.1e1 / t42;
  t46 = 0.2e1 * t14 * t43 * t15;
  t47 = t15 * t15;
  t48 = 0.1e1 / t47;
  t49 = t7 * t48;
  t51 = -rho[0] * t43 + t7;
  t56 = my_piecewise3(t10, 0, 0.2e1 * t39 * t15 - t46 + 0.2e1 / 0.3e1 * t14 * t49 * t51);
  t60 = t20 * t20;
  t61 = 0.1e1 / t60;
  t64 = t5 * t19 * t61 / 0.8e1;
  t66 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t56 * t20 - t64);
  t69 = 0.2e1 * t29 * t43 * t30;
  t70 = rho[1] * rho[1];
  t71 = t13 * t70;
  t72 = t42 * t6;
  t73 = 0.1e1 / t72;
  t74 = t30 * t30;
  t75 = 0.1e1 / t74;
  t76 = t73 * t75;
  t80 = my_piecewise3(t28, 0, -t69 - 0.2e1 / 0.3e1 * t71 * t76);
  t86 = t5 * t34 * t61 / 0.8e1;
  t88 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t80 * t20 - t86);
  tvrho0 = t24 + t38 + t6 * (t66 + t88);

  if(out->vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    out->vrho[ip*p->dim.vrho + 0] += tvrho0;

  t91 = rho[0] * rho[0];
  t92 = t13 * t91;
  t93 = t73 * t48;
  t97 = my_piecewise3(t10, 0, -t46 - 0.2e1 / 0.3e1 * t92 * t93);
  t102 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t97 * t20 - t64);
  t105 = t7 * t75;
  t107 = -rho[1] * t43 + t7;
  t112 = my_piecewise3(t28, 0, 0.2e1 * t39 * t30 - t69 + 0.2e1 / 0.3e1 * t29 * t105 * t107);
  t117 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t112 * t20 - t86);
  tvrho1 = t24 + t38 + t6 * (t102 + t117);

  if(out->vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    out->vrho[ip*p->dim.vrho + 1] += tvrho1;

}

#endif


#ifndef XC_DONT_COMPILE_FXC
GPU_DEVICE_FUNCTION static inline void
func_fxc_pol(const xc_func_type *p, size_t ip, const double *rho, xc_lda_out_params *out)
{
  double t1, t2, t3, t5, t6, t7, t8, t10;
  double t11, t12, t13, t14, t15, t19, t20, t24;
  double t25, t26, t28, t29, t30, t34, t38, tzk0;

  double t39, t42, t43, t46, t47, t48, t49, t51;
  double t56, t60, t61, t64, t66, t69, t70, t71;
  double t72, t73, t74, t75, t76, t80, t86, t88;
  double tvrho0, t91, t92, t93, t97, t102, t105, t107;
  double t112, t117, tvrho1;

  double t122, t123, t125, t130, t131, t133, t136, t137;
  double t138, t144, t149, t154, t157, t160, t162, t165;
  double t166, t167, t168, t169, t171, t172, t174, t176;
  double t177, t181, t186, t190, t192, tv2rho20, t199, t200;
  double t202, t203, t207, t212, t216, t217, t219, t220;
  double t224, t226, t228, t232, t234, t239, t244, t248;
  double tv2rho21, t254, t255, t256, t260, t266, t268, t272;
  double t273, t278, t283, t289, tv2rho22;


  t1 = rho[0] <= p->dens_threshold;
  t2 = M_CBRT3;
  t3 = M_CBRTPI;
  t5 = t2 / t3;
  t6 = rho[0] + rho[1];
  t7 = 0.1e1 / t6;
  t8 = rho[0] * t7;
  t10 = 0.2e1 * t8 <= p->zeta_threshold;
  t11 = POW_1_3(p->zeta_threshold);
  t12 = t11 * p->zeta_threshold;
  t13 = M_CBRT2;
  t14 = t13 * rho[0];
  t15 = POW_1_3(t8);
  t19 = my_piecewise3(t10, t12, 0.2e1 * t14 * t7 * t15);
  t20 = POW_1_3(t6);
  t24 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t19 * t20);
  t25 = rho[1] <= p->dens_threshold;
  t26 = rho[1] * t7;
  t28 = 0.2e1 * t26 <= p->zeta_threshold;
  t29 = t13 * rho[1];
  t30 = POW_1_3(t26);
  t34 = my_piecewise3(t28, t12, 0.2e1 * t29 * t7 * t30);
  t38 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t34 * t20);
  tzk0 = t24 + t38;

  if(out->zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    out->zk[ip*p->dim.zk + 0] += tzk0;

  t39 = t13 * t7;
  t42 = t6 * t6;
  t43 = 0.1e1 / t42;
  t46 = 0.2e1 * t14 * t43 * t15;
  t47 = t15 * t15;
  t48 = 0.1e1 / t47;
  t49 = t7 * t48;
  t51 = -rho[0] * t43 + t7;
  t56 = my_piecewise3(t10, 0, 0.2e1 * t39 * t15 - t46 + 0.2e1 / 0.3e1 * t14 * t49 * t51);
  t60 = t20 * t20;
  t61 = 0.1e1 / t60;
  t64 = t5 * t19 * t61 / 0.8e1;
  t66 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t56 * t20 - t64);
  t69 = 0.2e1 * t29 * t43 * t30;
  t70 = rho[1] * rho[1];
  t71 = t13 * t70;
  t72 = t42 * t6;
  t73 = 0.1e1 / t72;
  t74 = t30 * t30;
  t75 = 0.1e1 / t74;
  t76 = t73 * t75;
  t80 = my_piecewise3(t28, 0, -t69 - 0.2e1 / 0.3e1 * t71 * t76);
  t86 = t5 * t34 * t61 / 0.8e1;
  t88 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t80 * t20 - t86);
  tvrho0 = t24 + t38 + t6 * (t66 + t88);

  if(out->vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    out->vrho[ip*p->dim.vrho + 0] += tvrho0;

  t91 = rho[0] * rho[0];
  t92 = t13 * t91;
  t93 = t73 * t48;
  t97 = my_piecewise3(t10, 0, -t46 - 0.2e1 / 0.3e1 * t92 * t93);
  t102 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t97 * t20 - t64);
  t105 = t7 * t75;
  t107 = -rho[1] * t43 + t7;
  t112 = my_piecewise3(t28, 0, 0.2e1 * t39 * t30 - t69 + 0.2e1 / 0.3e1 * t29 * t105 * t107);
  t117 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t112 * t20 - t86);
  tvrho1 = t24 + t38 + t6 * (t102 + t117);

  if(out->vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    out->vrho[ip*p->dim.vrho + 1] += tvrho1;

  t122 = t13 * t43;
  t123 = t122 * t15;
  t125 = t48 * t51;
  t130 = 0.4e1 * t14 * t73 * t15;
  t131 = t43 * t48;
  t133 = t14 * t131 * t51;
  t136 = 0.1e1 / t47 / t8;
  t137 = t7 * t136;
  t138 = t51 * t51;
  t144 = 0.2e1 * rho[0] * t73 - 0.2e1 * t43;
  t149 = my_piecewise3(t10, 0, -0.4e1 * t123 + 0.4e1 / 0.3e1 * t39 * t125 + t130 - 0.4e1 / 0.3e1 * t133 - 0.4e1 / 0.9e1 * t14 * t137 * t138 + 0.2e1 / 0.3e1 * t14 * t49 * t144);
  t154 = t5 * t56 * t61;
  t157 = 0.1e1 / t60 / t6;
  t160 = t5 * t19 * t157 / 0.12e2;
  t162 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t149 * t20 - t154 / 0.4e1 + t160);
  t165 = 0.4e1 * t29 * t73 * t30;
  t166 = t42 * t42;
  t167 = 0.1e1 / t166;
  t168 = t167 * t75;
  t169 = t71 * t168;
  t171 = t70 * rho[1];
  t172 = t13 * t171;
  t174 = 0.1e1 / t166 / t6;
  t176 = 0.1e1 / t74 / t26;
  t177 = t174 * t176;
  t181 = my_piecewise3(t28, 0, t165 + 0.8e1 / 0.3e1 * t169 - 0.4e1 / 0.9e1 * t172 * t177);
  t186 = t5 * t80 * t61;
  t190 = t5 * t34 * t157 / 0.12e2;
  t192 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t181 * t20 - t186 / 0.4e1 + t190);
  tv2rho20 = 0.2e1 * t66 + 0.2e1 * t88 + t6 * (t162 + t192);

  if(out->v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    out->v2rho2[ip*p->dim.v2rho2 + 0] += tv2rho20;

  t199 = t167 * t48;
  t200 = t92 * t199;
  t202 = t73 * t136;
  t203 = t202 * t51;
  t207 = my_piecewise3(t10, 0, -0.2e1 * t123 + t130 - 0.2e1 / 0.3e1 * t133 - 0.4e1 / 0.3e1 * t14 * t93 + 0.2e1 * t200 + 0.4e1 / 0.9e1 * t92 * t203);
  t212 = t5 * t97 * t61;
  t216 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t207 * t20 - t212 / 0.8e1 - t154 / 0.8e1 + t160);
  t217 = t122 * t30;
  t219 = t13 * t73;
  t220 = t75 * rho[1];
  t224 = t43 * t75;
  t226 = t29 * t224 * t107;
  t228 = t73 * t176;
  t232 = rho[1] * t73;
  t234 = -t43 + 0.2e1 * t232;
  t239 = my_piecewise3(t28, 0, -0.2e1 * t217 - 0.2e1 / 0.3e1 * t219 * t220 + t165 + 0.2e1 / 0.3e1 * t169 - 0.2e1 / 0.3e1 * t226 + 0.4e1 / 0.9e1 * t71 * t228 * t107 + 0.2e1 / 0.3e1 * t29 * t105 * t234);
  t244 = t5 * t112 * t61;
  t248 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t239 * t20 - t244 / 0.8e1 - t186 / 0.8e1 + t190);
  tv2rho21 = t66 + t88 + t102 + t117 + t6 * (t216 + t248);

  if(out->v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    out->v2rho2[ip*p->dim.v2rho2 + 1] += tv2rho21;

  t254 = t91 * rho[0];
  t255 = t13 * t254;
  t256 = t174 * t136;
  t260 = my_piecewise3(t10, 0, t130 + 0.8e1 / 0.3e1 * t200 - 0.4e1 / 0.9e1 * t255 * t256);
  t266 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t260 * t20 - t212 / 0.4e1 + t160);
  t268 = t75 * t107;
  t272 = t7 * t176;
  t273 = t107 * t107;
  t278 = -0.2e1 * t43 + 0.2e1 * t232;
  t283 = my_piecewise3(t28, 0, -0.4e1 * t217 + 0.4e1 / 0.3e1 * t39 * t268 + t165 - 0.4e1 / 0.3e1 * t226 - 0.4e1 / 0.9e1 * t29 * t272 * t273 + 0.2e1 / 0.3e1 * t29 * t105 * t278);
  t289 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t283 * t20 - t244 / 0.4e1 + t190);
  tv2rho22 = 0.2e1 * t102 + 0.2e1 * t117 + t6 * (t266 + t289);

  if(out->v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    out->v2rho2[ip*p->dim.v2rho2 + 2] += tv2rho22;

}

#endif


#ifndef XC_DONT_COMPILE_KXC
GPU_DEVICE_FUNCTION static inline void
func_kxc_pol(const xc_func_type *p, size_t ip, const double *rho, xc_lda_out_params *out)
{
  double t1, t2, t3, t5, t6, t7, t8, t10;
  double t11, t12, t13, t14, t15, t19, t20, t24;
  double t25, t26, t28, t29, t30, t34, t38, tzk0;

  double t39, t42, t43, t46, t47, t48, t49, t51;
  double t56, t60, t61, t64, t66, t69, t70, t71;
  double t72, t73, t74, t75, t76, t80, t86, t88;
  double tvrho0, t91, t92, t93, t97, t102, t105, t107;
  double t112, t117, tvrho1;

  double t122, t123, t125, t130, t131, t133, t136, t137;
  double t138, t144, t149, t154, t157, t160, t162, t165;
  double t166, t167, t168, t169, t171, t172, t174, t176;
  double t177, t181, t186, t190, t192, tv2rho20, t199, t200;
  double t202, t203, t207, t212, t216, t217, t219, t220;
  double t224, t226, t228, t232, t234, t239, t244, t248;
  double tv2rho21, t254, t255, t256, t260, t266, t268, t272;
  double t273, t278, t283, t289, tv2rho22;

  double t294, t296, t298, t301, t306, t308, t312, t315;
  double t319, t321, t325, t326, t327, t332, t336, t337;
  double t342, t345, t348, t351, t353, t356, t358, t361;
  double t363, t365, t366, t368, t371, t376, t381, t384;
  double t388, t390, tv3rho30, t393, t394, t402, t406, t407;
  double t409, t410, t411, t414, t417, t420, t421, t427;
  double t429, t434, t435, t437, t438, t440, t441, t447;
  double t449, t451, t455, t456, t464, t465, t466, t470;
  double t471, t477, t479, t484, tv3rho31, t494, t495, t497;
  double t498, t502, t507, t512, t515, t517, t518, t521;
  double t529, t535, t536, t540, t546, t550, t551, t556;
  double t561, tv3rho32, t568, t569, t570, t574, t581, t584;
  double t587, t594, t598, t602, t606, t607, t614, tv3rho33;


  t1 = rho[0] <= p->dens_threshold;
  t2 = M_CBRT3;
  t3 = M_CBRTPI;
  t5 = t2 / t3;
  t6 = rho[0] + rho[1];
  t7 = 0.1e1 / t6;
  t8 = rho[0] * t7;
  t10 = 0.2e1 * t8 <= p->zeta_threshold;
  t11 = POW_1_3(p->zeta_threshold);
  t12 = t11 * p->zeta_threshold;
  t13 = M_CBRT2;
  t14 = t13 * rho[0];
  t15 = POW_1_3(t8);
  t19 = my_piecewise3(t10, t12, 0.2e1 * t14 * t7 * t15);
  t20 = POW_1_3(t6);
  t24 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t19 * t20);
  t25 = rho[1] <= p->dens_threshold;
  t26 = rho[1] * t7;
  t28 = 0.2e1 * t26 <= p->zeta_threshold;
  t29 = t13 * rho[1];
  t30 = POW_1_3(t26);
  t34 = my_piecewise3(t28, t12, 0.2e1 * t29 * t7 * t30);
  t38 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t34 * t20);
  tzk0 = t24 + t38;

  if(out->zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    out->zk[ip*p->dim.zk + 0] += tzk0;

  t39 = t13 * t7;
  t42 = t6 * t6;
  t43 = 0.1e1 / t42;
  t46 = 0.2e1 * t14 * t43 * t15;
  t47 = t15 * t15;
  t48 = 0.1e1 / t47;
  t49 = t7 * t48;
  t51 = -rho[0] * t43 + t7;
  t56 = my_piecewise3(t10, 0, 0.2e1 * t39 * t15 - t46 + 0.2e1 / 0.3e1 * t14 * t49 * t51);
  t60 = t20 * t20;
  t61 = 0.1e1 / t60;
  t64 = t5 * t19 * t61 / 0.8e1;
  t66 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t56 * t20 - t64);
  t69 = 0.2e1 * t29 * t43 * t30;
  t70 = rho[1] * rho[1];
  t71 = t13 * t70;
  t72 = t42 * t6;
  t73 = 0.1e1 / t72;
  t74 = t30 * t30;
  t75 = 0.1e1 / t74;
  t76 = t73 * t75;
  t80 = my_piecewise3(t28, 0, -t69 - 0.2e1 / 0.3e1 * t71 * t76);
  t86 = t5 * t34 * t61 / 0.8e1;
  t88 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t80 * t20 - t86);
  tvrho0 = t24 + t38 + t6 * (t66 + t88);

  if(out->vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    out->vrho[ip*p->dim.vrho + 0] += tvrho0;

  t91 = rho[0] * rho[0];
  t92 = t13 * t91;
  t93 = t73 * t48;
  t97 = my_piecewise3(t10, 0, -t46 - 0.2e1 / 0.3e1 * t92 * t93);
  t102 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t97 * t20 - t64);
  t105 = t7 * t75;
  t107 = -rho[1] * t43 + t7;
  t112 = my_piecewise3(t28, 0, 0.2e1 * t39 * t30 - t69 + 0.2e1 / 0.3e1 * t29 * t105 * t107);
  t117 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t112 * t20 - t86);
  tvrho1 = t24 + t38 + t6 * (t102 + t117);

  if(out->vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    out->vrho[ip*p->dim.vrho + 1] += tvrho1;

  t122 = t13 * t43;
  t123 = t122 * t15;
  t125 = t48 * t51;
  t130 = 0.4e1 * t14 * t73 * t15;
  t131 = t43 * t48;
  t133 = t14 * t131 * t51;
  t136 = 0.1e1 / t47 / t8;
  t137 = t7 * t136;
  t138 = t51 * t51;
  t144 = 0.2e1 * rho[0] * t73 - 0.2e1 * t43;
  t149 = my_piecewise3(t10, 0, -0.4e1 * t123 + 0.4e1 / 0.3e1 * t39 * t125 + t130 - 0.4e1 / 0.3e1 * t133 - 0.4e1 / 0.9e1 * t14 * t137 * t138 + 0.2e1 / 0.3e1 * t14 * t49 * t144);
  t154 = t5 * t56 * t61;
  t157 = 0.1e1 / t60 / t6;
  t160 = t5 * t19 * t157 / 0.12e2;
  t162 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t149 * t20 - t154 / 0.4e1 + t160);
  t165 = 0.4e1 * t29 * t73 * t30;
  t166 = t42 * t42;
  t167 = 0.1e1 / t166;
  t168 = t167 * t75;
  t169 = t71 * t168;
  t171 = t70 * rho[1];
  t172 = t13 * t171;
  t174 = 0.1e1 / t166 / t6;
  t176 = 0.1e1 / t74 / t26;
  t177 = t174 * t176;
  t181 = my_piecewise3(t28, 0, t165 + 0.8e1 / 0.3e1 * t169 - 0.4e1 / 0.9e1 * t172 * t177);
  t186 = t5 * t80 * t61;
  t190 = t5 * t34 * t157 / 0.12e2;
  t192 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t181 * t20 - t186 / 0.4e1 + t190);
  tv2rho20 = 0.2e1 * t66 + 0.2e1 * t88 + t6 * (t162 + t192);

  if(out->v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    out->v2rho2[ip*p->dim.v2rho2 + 0] += tv2rho20;

  t199 = t167 * t48;
  t200 = t92 * t199;
  t202 = t73 * t136;
  t203 = t202 * t51;
  t207 = my_piecewise3(t10, 0, -0.2e1 * t123 + t130 - 0.2e1 / 0.3e1 * t133 - 0.4e1 / 0.3e1 * t14 * t93 + 0.2e1 * t200 + 0.4e1 / 0.9e1 * t92 * t203);
  t212 = t5 * t97 * t61;
  t216 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t207 * t20 - t212 / 0.8e1 - t154 / 0.8e1 + t160);
  t217 = t122 * t30;
  t219 = t13 * t73;
  t220 = t75 * rho[1];
  t224 = t43 * t75;
  t226 = t29 * t224 * t107;
  t228 = t73 * t176;
  t232 = rho[1] * t73;
  t234 = -t43 + 0.2e1 * t232;
  t239 = my_piecewise3(t28, 0, -0.2e1 * t217 - 0.2e1 / 0.3e1 * t219 * t220 + t165 + 0.2e1 / 0.3e1 * t169 - 0.2e1 / 0.3e1 * t226 + 0.4e1 / 0.9e1 * t71 * t228 * t107 + 0.2e1 / 0.3e1 * t29 * t105 * t234);
  t244 = t5 * t112 * t61;
  t248 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t239 * t20 - t244 / 0.8e1 - t186 / 0.8e1 + t190);
  tv2rho21 = t66 + t88 + t102 + t117 + t6 * (t216 + t248);

  if(out->v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    out->v2rho2[ip*p->dim.v2rho2 + 1] += tv2rho21;

  t254 = t91 * rho[0];
  t255 = t13 * t254;
  t256 = t174 * t136;
  t260 = my_piecewise3(t10, 0, t130 + 0.8e1 / 0.3e1 * t200 - 0.4e1 / 0.9e1 * t255 * t256);
  t266 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t260 * t20 - t212 / 0.4e1 + t160);
  t268 = t75 * t107;
  t272 = t7 * t176;
  t273 = t107 * t107;
  t278 = -0.2e1 * t43 + 0.2e1 * t232;
  t283 = my_piecewise3(t28, 0, -0.4e1 * t217 + 0.4e1 / 0.3e1 * t39 * t268 + t165 - 0.4e1 / 0.3e1 * t226 - 0.4e1 / 0.9e1 * t29 * t272 * t273 + 0.2e1 / 0.3e1 * t29 * t105 * t278);
  t289 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t283 * t20 - t244 / 0.4e1 + t190);
  tv2rho22 = 0.2e1 * t102 + 0.2e1 * t117 + t6 * (t266 + t289);

  if(out->v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    out->v2rho2[ip*p->dim.v2rho2 + 2] += tv2rho22;

  t294 = t219 * t15;
  t296 = t122 * t125;
  t298 = t136 * t138;
  t301 = t48 * t144;
  t306 = 0.12e2 * t14 * t167 * t15;
  t308 = t14 * t93 * t51;
  t312 = t14 * t43 * t136 * t138;
  t315 = t14 * t131 * t144;
  t319 = 0.1e1 / t47 / t91 / t43;
  t321 = t138 * t51;
  t325 = t14 * t7;
  t326 = t136 * t51;
  t327 = t326 * t144;
  t332 = -0.6e1 * rho[0] * t167 + 0.6e1 * t73;
  t336 = 0.12e2 * t294 - 0.4e1 * t296 - 0.4e1 / 0.3e1 * t39 * t298 + 0.2e1 * t39 * t301 - t306 + 0.4e1 * t308 + 0.4e1 / 0.3e1 * t312 - 0.2e1 * t315 + 0.2e2 / 0.27e2 * t14 * t7 * t319 * t321 - 0.4e1 / 0.3e1 * t325 * t327 + 0.2e1 / 0.3e1 * t14 * t49 * t332;
  t337 = my_piecewise3(t10, 0, t336);
  t342 = t5 * t149 * t61;
  t345 = t5 * t56 * t157;
  t348 = 0.1e1 / t60 / t42;
  t351 = 0.5e1 / 0.36e2 * t5 * t19 * t348;
  t353 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t337 * t20 - 0.3e1 / 0.8e1 * t342 + t345 / 0.4e1 - t351);
  t356 = 0.12e2 * t29 * t167 * t30;
  t358 = t71 * t174 * t75;
  t361 = 0.1e1 / t166 / t42;
  t363 = t172 * t361 * t176;
  t365 = t70 * t70;
  t366 = t13 * t365;
  t368 = 0.1e1 / t166 / t72;
  t371 = 0.1e1 / t74 / t70 / t43;
  t376 = my_piecewise3(t28, 0, -t356 - 0.12e2 * t358 + 0.4e1 * t363 - 0.2e2 / 0.27e2 * t366 * t368 * t371);
  t381 = t5 * t181 * t61;
  t384 = t5 * t80 * t157;
  t388 = 0.5e1 / 0.36e2 * t5 * t34 * t348;
  t390 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t376 * t20 - 0.3e1 / 0.8e1 * t381 + t384 / 0.4e1 - t388);
  tv3rho30 = 0.3e1 * t162 + 0.3e1 * t192 + t6 * (t353 + t390);

  if(out->v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    out->v3rho3[ip*p->dim.v3rho3 + 0] += tv3rho30;

  t393 = 0.2e1 * t216;
  t394 = 0.2e1 * t248;
  t402 = t14 * t199;
  t406 = t174 * t48;
  t407 = t92 * t406;
  t409 = t167 * t136;
  t410 = t409 * t51;
  t411 = t92 * t410;
  t414 = t73 * t319 * t138;
  t417 = t202 * t144;
  t420 = 0.8e1 * t294 - 0.4e1 / 0.3e1 * t296 - t306 + 0.8e1 / 0.3e1 * t308 + 0.4e1 / 0.9e1 * t312 - 0.2e1 / 0.3e1 * t315 - 0.4e1 / 0.3e1 * t219 * t48 + 0.8e1 * t402 + 0.16e2 / 0.9e1 * t14 * t203 - 0.8e1 * t407 - 0.8e1 / 0.3e1 * t411 - 0.2e2 / 0.27e2 * t92 * t414 + 0.4e1 / 0.9e1 * t92 * t417;
  t421 = my_piecewise3(t10, 0, t420);
  t427 = t5 * t207 * t61 / 0.4e1;
  t429 = t5 * t97 * t157;
  t434 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t421 * t20 - t427 + t429 / 0.12e2 - t342 / 0.8e1 + t345 / 0.6e1 - t351);
  t435 = t219 * t30;
  t437 = t13 * t167;
  t438 = t437 * t220;
  t440 = t13 * t174;
  t441 = t176 * t70;
  t447 = t29 * t76 * t107;
  t449 = t167 * t176;
  t451 = t71 * t449 * t107;
  t455 = 0.4e1 / 0.3e1 * t29 * t224 * t234;
  t456 = t174 * t371;
  t464 = rho[1] * t167;
  t465 = 0.6e1 * t464;
  t466 = 0.2e1 * t73 - t465;
  t470 = 0.4e1 * t435 + 0.8e1 / 0.3e1 * t438 - 0.4e1 / 0.9e1 * t440 * t441 - t356 - 0.4e1 * t358 + 0.4e1 / 0.9e1 * t363 + 0.4e1 / 0.3e1 * t447 - 0.16e2 / 0.9e1 * t451 - t455 + 0.2e2 / 0.27e2 * t172 * t456 * t107 + 0.8e1 / 0.9e1 * t71 * t228 * t234 + 0.2e1 / 0.3e1 * t29 * t105 * t466;
  t471 = my_piecewise3(t28, 0, t470);
  t477 = t5 * t239 * t61 / 0.4e1;
  t479 = t5 * t112 * t157;
  t484 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t471 * t20 - t477 + t479 / 0.12e2 - t381 / 0.8e1 + t384 / 0.6e1 - t388);
  tv3rho31 = t162 + t192 + t393 + t394 + t6 * (t434 + t484);

  if(out->v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    out->v3rho3[ip*p->dim.v3rho3 + 1] += tv3rho31;

  t494 = t361 * t136;
  t495 = t255 * t494;
  t497 = t174 * t319;
  t498 = t497 * t51;
  t502 = my_piecewise3(t10, 0, 0.4e1 * t294 - t306 + 0.4e1 / 0.3e1 * t308 + 0.16e2 / 0.3e1 * t402 - 0.32e2 / 0.3e1 * t407 - 0.16e2 / 0.9e1 * t411 - 0.4e1 / 0.3e1 * t92 * t256 + 0.2e2 / 0.9e1 * t495 + 0.2e2 / 0.27e2 * t255 * t498);
  t507 = t5 * t260 * t61;
  t512 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t502 * t20 - t507 / 0.8e1 - t427 + t429 / 0.6e1 + t345 / 0.12e2 - t351);
  t515 = t122 * t268;
  t517 = t176 * t107;
  t518 = t517 * rho[1];
  t521 = t75 * t234;
  t529 = t29 * t43 * t176 * t273;
  t535 = t29 * t7;
  t536 = t517 * t234;
  t540 = t29 * t224 * t278;
  t546 = 0.4e1 * t73 - t465;
  t550 = 0.8e1 * t435 + 0.4e1 / 0.3e1 * t438 - 0.4e1 / 0.3e1 * t515 + 0.8e1 / 0.9e1 * t219 * t518 + 0.4e1 / 0.3e1 * t39 * t521 - t356 - 0.4e1 / 0.3e1 * t358 + 0.8e1 / 0.3e1 * t447 - 0.8e1 / 0.9e1 * t451 - t455 + 0.4e1 / 0.9e1 * t529 - 0.2e2 / 0.27e2 * t71 * t73 * t371 * t273 - 0.8e1 / 0.9e1 * t535 * t536 - 0.2e1 / 0.3e1 * t540 + 0.4e1 / 0.9e1 * t71 * t228 * t278 + 0.2e1 / 0.3e1 * t29 * t105 * t546;
  t551 = my_piecewise3(t28, 0, t550);
  t556 = t5 * t283 * t61;
  t561 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t551 * t20 - t556 / 0.8e1 - t477 + t479 / 0.6e1 + t384 / 0.12e2 - t388);
  tv3rho32 = t393 + t394 + t266 + t289 + t6 * (t512 + t561);

  if(out->v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    out->v3rho3[ip*p->dim.v3rho3 + 2] += tv3rho32;

  t568 = t91 * t91;
  t569 = t13 * t568;
  t570 = t368 * t319;
  t574 = my_piecewise3(t10, 0, -t306 - 0.12e2 * t407 + 0.4e1 * t495 - 0.2e2 / 0.27e2 * t569 * t570);
  t581 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t574 * t20 - 0.3e1 / 0.8e1 * t507 + t429 / 0.4e1 - t351);
  t584 = t176 * t273;
  t587 = t75 * t278;
  t594 = t273 * t107;
  t598 = t517 * t278;
  t602 = 0.6e1 * t73 - 0.6e1 * t464;
  t606 = 0.12e2 * t435 - 0.4e1 * t515 - 0.4e1 / 0.3e1 * t39 * t584 + 0.2e1 * t39 * t587 - t356 + 0.4e1 * t447 + 0.4e1 / 0.3e1 * t529 - 0.2e1 * t540 + 0.2e2 / 0.27e2 * t29 * t7 * t371 * t594 - 0.4e1 / 0.3e1 * t535 * t598 + 0.2e1 / 0.3e1 * t29 * t105 * t602;
  t607 = my_piecewise3(t28, 0, t606);
  t614 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t607 * t20 - 0.3e1 / 0.8e1 * t556 + t479 / 0.4e1 - t388);
  tv3rho33 = 0.3e1 * t266 + 0.3e1 * t289 + t6 * (t581 + t614);

  if(out->v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    out->v3rho3[ip*p->dim.v3rho3 + 3] += tv3rho33;

}

#endif


#ifndef XC_DONT_COMPILE_LXC
GPU_DEVICE_FUNCTION static inline void
func_lxc_pol(const xc_func_type *p, size_t ip, const double *rho, xc_lda_out_params *out)
{
  double t1, t2, t3, t5, t6, t7, t8, t10;
  double t11, t12, t13, t14, t15, t19, t20, t24;
  double t25, t26, t28, t29, t30, t34, t38, tzk0;

  double t39, t42, t43, t46, t47, t48, t49, t51;
  double t56, t60, t61, t64, t66, t69, t70, t71;
  double t72, t73, t74, t75, t76, t80, t86, t88;
  double tvrho0, t91, t92, t93, t97, t102, t105, t107;
  double t112, t117, tvrho1;

  double t122, t123, t125, t130, t131, t133, t136, t137;
  double t138, t144, t149, t154, t157, t160, t162, t165;
  double t166, t167, t168, t169, t171, t172, t174, t176;
  double t177, t181, t186, t190, t192, tv2rho20, t199, t200;
  double t202, t203, t207, t212, t216, t217, t219, t220;
  double t224, t226, t228, t232, t234, t239, t244, t248;
  double tv2rho21, t254, t255, t256, t260, t266, t268, t272;
  double t273, t278, t283, t289, tv2rho22;

  double t294, t296, t298, t301, t306, t308, t312, t315;
  double t319, t321, t325, t326, t327, t332, t336, t337;
  double t342, t345, t348, t351, t353, t356, t358, t361;
  double t363, t365, t366, t368, t371, t376, t381, t384;
  double t388, t390, tv3rho30, t393, t394, t402, t406, t407;
  double t409, t410, t411, t414, t417, t420, t421, t427;
  double t429, t434, t435, t437, t438, t440, t441, t447;
  double t449, t451, t455, t456, t464, t465, t466, t470;
  double t471, t477, t479, t484, tv3rho31, t494, t495, t497;
  double t498, t502, t507, t512, t515, t517, t518, t521;
  double t529, t535, t536, t540, t546, t550, t551, t556;
  double t561, tv3rho32, t568, t569, t570, t574, t581, t584;
  double t587, t594, t598, t602, t606, t607, t614, tv3rho33;

  double t619, t628, t630, t633, t636, t645, t649, t652;
  double t656, t658, t666, t673, t675, t677, t682, t683;
  double t688, t691, t694, t697, t700, t702, t705, t707;
  double t710, t712, t713, t715, t720, t723, t728, t733;
  double t736, t739, t743, t745, tv4rho40, t750, t752, t757;
  double t760, t763, t772, t777, t794, t798, t800, t805;
  double t808, t809, t811, t817, t826, t827, t833, t834;
  double t836, t839, t843, t846, t852, t857, t859, t862;
  double t868, t869, t874, t877, t878, t880, t886, tv4rho41;
  double t895, t900, t904, t925, t926, t931, t934, t942;
  double t943, t944, t946, t947, t956, t969, t971, t976;
  double t978, t983, t990, t992, t998, t1008, t1013, t1017;
  double t1019, t1024, t1027, t1035, tv4rho42, t1051, t1057, t1058;
  double t1063, t1070, t1071, t1084, t1111, t1114, t1117, t1128;
  double t1130, t1136, t1138, t1143, t1150, tv4rho43, t1164, t1172;
  double t1190, t1197, t1211, t1212, t1220, tv4rho44;


  t1 = rho[0] <= p->dens_threshold;
  t2 = M_CBRT3;
  t3 = M_CBRTPI;
  t5 = t2 / t3;
  t6 = rho[0] + rho[1];
  t7 = 0.1e1 / t6;
  t8 = rho[0] * t7;
  t10 = 0.2e1 * t8 <= p->zeta_threshold;
  t11 = POW_1_3(p->zeta_threshold);
  t12 = t11 * p->zeta_threshold;
  t13 = M_CBRT2;
  t14 = t13 * rho[0];
  t15 = POW_1_3(t8);
  t19 = my_piecewise3(t10, t12, 0.2e1 * t14 * t7 * t15);
  t20 = POW_1_3(t6);
  t24 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t19 * t20);
  t25 = rho[1] <= p->dens_threshold;
  t26 = rho[1] * t7;
  t28 = 0.2e1 * t26 <= p->zeta_threshold;
  t29 = t13 * rho[1];
  t30 = POW_1_3(t26);
  t34 = my_piecewise3(t28, t12, 0.2e1 * t29 * t7 * t30);
  t38 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t34 * t20);
  tzk0 = t24 + t38;

  if(out->zk != NULL && (p->info->flags & XC_FLAGS_HAVE_EXC))
    out->zk[ip*p->dim.zk + 0] += tzk0;

  t39 = t13 * t7;
  t42 = t6 * t6;
  t43 = 0.1e1 / t42;
  t46 = 0.2e1 * t14 * t43 * t15;
  t47 = t15 * t15;
  t48 = 0.1e1 / t47;
  t49 = t7 * t48;
  t51 = -rho[0] * t43 + t7;
  t56 = my_piecewise3(t10, 0, 0.2e1 * t39 * t15 - t46 + 0.2e1 / 0.3e1 * t14 * t49 * t51);
  t60 = t20 * t20;
  t61 = 0.1e1 / t60;
  t64 = t5 * t19 * t61 / 0.8e1;
  t66 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t56 * t20 - t64);
  t69 = 0.2e1 * t29 * t43 * t30;
  t70 = rho[1] * rho[1];
  t71 = t13 * t70;
  t72 = t42 * t6;
  t73 = 0.1e1 / t72;
  t74 = t30 * t30;
  t75 = 0.1e1 / t74;
  t76 = t73 * t75;
  t80 = my_piecewise3(t28, 0, -t69 - 0.2e1 / 0.3e1 * t71 * t76);
  t86 = t5 * t34 * t61 / 0.8e1;
  t88 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t80 * t20 - t86);
  tvrho0 = t24 + t38 + t6 * (t66 + t88);

  if(out->vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    out->vrho[ip*p->dim.vrho + 0] += tvrho0;

  t91 = rho[0] * rho[0];
  t92 = t13 * t91;
  t93 = t73 * t48;
  t97 = my_piecewise3(t10, 0, -t46 - 0.2e1 / 0.3e1 * t92 * t93);
  t102 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t97 * t20 - t64);
  t105 = t7 * t75;
  t107 = -rho[1] * t43 + t7;
  t112 = my_piecewise3(t28, 0, 0.2e1 * t39 * t30 - t69 + 0.2e1 / 0.3e1 * t29 * t105 * t107);
  t117 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t112 * t20 - t86);
  tvrho1 = t24 + t38 + t6 * (t102 + t117);

  if(out->vrho != NULL && (p->info->flags & XC_FLAGS_HAVE_VXC))
    out->vrho[ip*p->dim.vrho + 1] += tvrho1;

  t122 = t13 * t43;
  t123 = t122 * t15;
  t125 = t48 * t51;
  t130 = 0.4e1 * t14 * t73 * t15;
  t131 = t43 * t48;
  t133 = t14 * t131 * t51;
  t136 = 0.1e1 / t47 / t8;
  t137 = t7 * t136;
  t138 = t51 * t51;
  t144 = 0.2e1 * rho[0] * t73 - 0.2e1 * t43;
  t149 = my_piecewise3(t10, 0, -0.4e1 * t123 + 0.4e1 / 0.3e1 * t39 * t125 + t130 - 0.4e1 / 0.3e1 * t133 - 0.4e1 / 0.9e1 * t14 * t137 * t138 + 0.2e1 / 0.3e1 * t14 * t49 * t144);
  t154 = t5 * t56 * t61;
  t157 = 0.1e1 / t60 / t6;
  t160 = t5 * t19 * t157 / 0.12e2;
  t162 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t149 * t20 - t154 / 0.4e1 + t160);
  t165 = 0.4e1 * t29 * t73 * t30;
  t166 = t42 * t42;
  t167 = 0.1e1 / t166;
  t168 = t167 * t75;
  t169 = t71 * t168;
  t171 = t70 * rho[1];
  t172 = t13 * t171;
  t174 = 0.1e1 / t166 / t6;
  t176 = 0.1e1 / t74 / t26;
  t177 = t174 * t176;
  t181 = my_piecewise3(t28, 0, t165 + 0.8e1 / 0.3e1 * t169 - 0.4e1 / 0.9e1 * t172 * t177);
  t186 = t5 * t80 * t61;
  t190 = t5 * t34 * t157 / 0.12e2;
  t192 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t181 * t20 - t186 / 0.4e1 + t190);
  tv2rho20 = 0.2e1 * t66 + 0.2e1 * t88 + t6 * (t162 + t192);

  if(out->v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    out->v2rho2[ip*p->dim.v2rho2 + 0] += tv2rho20;

  t199 = t167 * t48;
  t200 = t92 * t199;
  t202 = t73 * t136;
  t203 = t202 * t51;
  t207 = my_piecewise3(t10, 0, -0.2e1 * t123 + t130 - 0.2e1 / 0.3e1 * t133 - 0.4e1 / 0.3e1 * t14 * t93 + 0.2e1 * t200 + 0.4e1 / 0.9e1 * t92 * t203);
  t212 = t5 * t97 * t61;
  t216 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t207 * t20 - t212 / 0.8e1 - t154 / 0.8e1 + t160);
  t217 = t122 * t30;
  t219 = t13 * t73;
  t220 = t75 * rho[1];
  t224 = t43 * t75;
  t226 = t29 * t224 * t107;
  t228 = t73 * t176;
  t232 = rho[1] * t73;
  t234 = -t43 + 0.2e1 * t232;
  t239 = my_piecewise3(t28, 0, -0.2e1 * t217 - 0.2e1 / 0.3e1 * t219 * t220 + t165 + 0.2e1 / 0.3e1 * t169 - 0.2e1 / 0.3e1 * t226 + 0.4e1 / 0.9e1 * t71 * t228 * t107 + 0.2e1 / 0.3e1 * t29 * t105 * t234);
  t244 = t5 * t112 * t61;
  t248 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t239 * t20 - t244 / 0.8e1 - t186 / 0.8e1 + t190);
  tv2rho21 = t66 + t88 + t102 + t117 + t6 * (t216 + t248);

  if(out->v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    out->v2rho2[ip*p->dim.v2rho2 + 1] += tv2rho21;

  t254 = t91 * rho[0];
  t255 = t13 * t254;
  t256 = t174 * t136;
  t260 = my_piecewise3(t10, 0, t130 + 0.8e1 / 0.3e1 * t200 - 0.4e1 / 0.9e1 * t255 * t256);
  t266 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t260 * t20 - t212 / 0.4e1 + t160);
  t268 = t75 * t107;
  t272 = t7 * t176;
  t273 = t107 * t107;
  t278 = -0.2e1 * t43 + 0.2e1 * t232;
  t283 = my_piecewise3(t28, 0, -0.4e1 * t217 + 0.4e1 / 0.3e1 * t39 * t268 + t165 - 0.4e1 / 0.3e1 * t226 - 0.4e1 / 0.9e1 * t29 * t272 * t273 + 0.2e1 / 0.3e1 * t29 * t105 * t278);
  t289 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t283 * t20 - t244 / 0.4e1 + t190);
  tv2rho22 = 0.2e1 * t102 + 0.2e1 * t117 + t6 * (t266 + t289);

  if(out->v2rho2 != NULL && (p->info->flags & XC_FLAGS_HAVE_FXC))
    out->v2rho2[ip*p->dim.v2rho2 + 2] += tv2rho22;

  t294 = t219 * t15;
  t296 = t122 * t125;
  t298 = t136 * t138;
  t301 = t48 * t144;
  t306 = 0.12e2 * t14 * t167 * t15;
  t308 = t14 * t93 * t51;
  t312 = t14 * t43 * t136 * t138;
  t315 = t14 * t131 * t144;
  t319 = 0.1e1 / t47 / t91 / t43;
  t321 = t138 * t51;
  t325 = t14 * t7;
  t326 = t136 * t51;
  t327 = t326 * t144;
  t332 = -0.6e1 * rho[0] * t167 + 0.6e1 * t73;
  t336 = 0.12e2 * t294 - 0.4e1 * t296 - 0.4e1 / 0.3e1 * t39 * t298 + 0.2e1 * t39 * t301 - t306 + 0.4e1 * t308 + 0.4e1 / 0.3e1 * t312 - 0.2e1 * t315 + 0.2e2 / 0.27e2 * t14 * t7 * t319 * t321 - 0.4e1 / 0.3e1 * t325 * t327 + 0.2e1 / 0.3e1 * t14 * t49 * t332;
  t337 = my_piecewise3(t10, 0, t336);
  t342 = t5 * t149 * t61;
  t345 = t5 * t56 * t157;
  t348 = 0.1e1 / t60 / t42;
  t351 = 0.5e1 / 0.36e2 * t5 * t19 * t348;
  t353 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t337 * t20 - 0.3e1 / 0.8e1 * t342 + t345 / 0.4e1 - t351);
  t356 = 0.12e2 * t29 * t167 * t30;
  t358 = t71 * t174 * t75;
  t361 = 0.1e1 / t166 / t42;
  t363 = t172 * t361 * t176;
  t365 = t70 * t70;
  t366 = t13 * t365;
  t368 = 0.1e1 / t166 / t72;
  t371 = 0.1e1 / t74 / t70 / t43;
  t376 = my_piecewise3(t28, 0, -t356 - 0.12e2 * t358 + 0.4e1 * t363 - 0.2e2 / 0.27e2 * t366 * t368 * t371);
  t381 = t5 * t181 * t61;
  t384 = t5 * t80 * t157;
  t388 = 0.5e1 / 0.36e2 * t5 * t34 * t348;
  t390 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t376 * t20 - 0.3e1 / 0.8e1 * t381 + t384 / 0.4e1 - t388);
  tv3rho30 = 0.3e1 * t162 + 0.3e1 * t192 + t6 * (t353 + t390);

  if(out->v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    out->v3rho3[ip*p->dim.v3rho3 + 0] += tv3rho30;

  t393 = 0.2e1 * t216;
  t394 = 0.2e1 * t248;
  t402 = t14 * t199;
  t406 = t174 * t48;
  t407 = t92 * t406;
  t409 = t167 * t136;
  t410 = t409 * t51;
  t411 = t92 * t410;
  t414 = t73 * t319 * t138;
  t417 = t202 * t144;
  t420 = 0.8e1 * t294 - 0.4e1 / 0.3e1 * t296 - t306 + 0.8e1 / 0.3e1 * t308 + 0.4e1 / 0.9e1 * t312 - 0.2e1 / 0.3e1 * t315 - 0.4e1 / 0.3e1 * t219 * t48 + 0.8e1 * t402 + 0.16e2 / 0.9e1 * t14 * t203 - 0.8e1 * t407 - 0.8e1 / 0.3e1 * t411 - 0.2e2 / 0.27e2 * t92 * t414 + 0.4e1 / 0.9e1 * t92 * t417;
  t421 = my_piecewise3(t10, 0, t420);
  t427 = t5 * t207 * t61 / 0.4e1;
  t429 = t5 * t97 * t157;
  t434 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t421 * t20 - t427 + t429 / 0.12e2 - t342 / 0.8e1 + t345 / 0.6e1 - t351);
  t435 = t219 * t30;
  t437 = t13 * t167;
  t438 = t437 * t220;
  t440 = t13 * t174;
  t441 = t176 * t70;
  t447 = t29 * t76 * t107;
  t449 = t167 * t176;
  t451 = t71 * t449 * t107;
  t455 = 0.4e1 / 0.3e1 * t29 * t224 * t234;
  t456 = t174 * t371;
  t464 = rho[1] * t167;
  t465 = 0.6e1 * t464;
  t466 = 0.2e1 * t73 - t465;
  t470 = 0.4e1 * t435 + 0.8e1 / 0.3e1 * t438 - 0.4e1 / 0.9e1 * t440 * t441 - t356 - 0.4e1 * t358 + 0.4e1 / 0.9e1 * t363 + 0.4e1 / 0.3e1 * t447 - 0.16e2 / 0.9e1 * t451 - t455 + 0.2e2 / 0.27e2 * t172 * t456 * t107 + 0.8e1 / 0.9e1 * t71 * t228 * t234 + 0.2e1 / 0.3e1 * t29 * t105 * t466;
  t471 = my_piecewise3(t28, 0, t470);
  t477 = t5 * t239 * t61 / 0.4e1;
  t479 = t5 * t112 * t157;
  t484 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t471 * t20 - t477 + t479 / 0.12e2 - t381 / 0.8e1 + t384 / 0.6e1 - t388);
  tv3rho31 = t162 + t192 + t393 + t394 + t6 * (t434 + t484);

  if(out->v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    out->v3rho3[ip*p->dim.v3rho3 + 1] += tv3rho31;

  t494 = t361 * t136;
  t495 = t255 * t494;
  t497 = t174 * t319;
  t498 = t497 * t51;
  t502 = my_piecewise3(t10, 0, 0.4e1 * t294 - t306 + 0.4e1 / 0.3e1 * t308 + 0.16e2 / 0.3e1 * t402 - 0.32e2 / 0.3e1 * t407 - 0.16e2 / 0.9e1 * t411 - 0.4e1 / 0.3e1 * t92 * t256 + 0.2e2 / 0.9e1 * t495 + 0.2e2 / 0.27e2 * t255 * t498);
  t507 = t5 * t260 * t61;
  t512 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t502 * t20 - t507 / 0.8e1 - t427 + t429 / 0.6e1 + t345 / 0.12e2 - t351);
  t515 = t122 * t268;
  t517 = t176 * t107;
  t518 = t517 * rho[1];
  t521 = t75 * t234;
  t529 = t29 * t43 * t176 * t273;
  t535 = t29 * t7;
  t536 = t517 * t234;
  t540 = t29 * t224 * t278;
  t546 = 0.4e1 * t73 - t465;
  t550 = 0.8e1 * t435 + 0.4e1 / 0.3e1 * t438 - 0.4e1 / 0.3e1 * t515 + 0.8e1 / 0.9e1 * t219 * t518 + 0.4e1 / 0.3e1 * t39 * t521 - t356 - 0.4e1 / 0.3e1 * t358 + 0.8e1 / 0.3e1 * t447 - 0.8e1 / 0.9e1 * t451 - t455 + 0.4e1 / 0.9e1 * t529 - 0.2e2 / 0.27e2 * t71 * t73 * t371 * t273 - 0.8e1 / 0.9e1 * t535 * t536 - 0.2e1 / 0.3e1 * t540 + 0.4e1 / 0.9e1 * t71 * t228 * t278 + 0.2e1 / 0.3e1 * t29 * t105 * t546;
  t551 = my_piecewise3(t28, 0, t550);
  t556 = t5 * t283 * t61;
  t561 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t551 * t20 - t556 / 0.8e1 - t477 + t479 / 0.6e1 + t384 / 0.12e2 - t388);
  tv3rho32 = t393 + t394 + t266 + t289 + t6 * (t512 + t561);

  if(out->v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    out->v3rho3[ip*p->dim.v3rho3 + 2] += tv3rho32;

  t568 = t91 * t91;
  t569 = t13 * t568;
  t570 = t368 * t319;
  t574 = my_piecewise3(t10, 0, -t306 - 0.12e2 * t407 + 0.4e1 * t495 - 0.2e2 / 0.27e2 * t569 * t570);
  t581 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t574 * t20 - 0.3e1 / 0.8e1 * t507 + t429 / 0.4e1 - t351);
  t584 = t176 * t273;
  t587 = t75 * t278;
  t594 = t273 * t107;
  t598 = t517 * t278;
  t602 = 0.6e1 * t73 - 0.6e1 * t464;
  t606 = 0.12e2 * t435 - 0.4e1 * t515 - 0.4e1 / 0.3e1 * t39 * t584 + 0.2e1 * t39 * t587 - t356 + 0.4e1 * t447 + 0.4e1 / 0.3e1 * t529 - 0.2e1 * t540 + 0.2e2 / 0.27e2 * t29 * t7 * t371 * t594 - 0.4e1 / 0.3e1 * t535 * t598 + 0.2e1 / 0.3e1 * t29 * t105 * t602;
  t607 = my_piecewise3(t28, 0, t606);
  t614 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t607 * t20 - 0.3e1 / 0.8e1 * t556 + t479 / 0.4e1 - t388);
  tv3rho33 = 0.3e1 * t266 + 0.3e1 * t289 + t6 * (t581 + t614);

  if(out->v3rho3 != NULL && (p->info->flags & XC_FLAGS_HAVE_KXC))
    out->v3rho3[ip*p->dim.v3rho3 + 3] += tv3rho33;

  t619 = t122 * t298;
  t628 = 0.48e2 * t14 * t174 * t15;
  t630 = t14 * t199 * t51;
  t633 = t14 * t93 * t144;
  t636 = t14 * t131 * t332;
  t645 = t14 * t202 * t138;
  t649 = t14 * t43 * t319 * t321;
  t652 = t14 * t43 * t327;
  t656 = 0.1e1 / t47 / t254 / t73;
  t658 = t138 * t138;
  t666 = t144 * t144;
  t673 = t437 * t15;
  t675 = t219 * t125;
  t677 = t122 * t301;
  t682 = 0.16e2 / 0.3e1 * t619 + 0.8e2 / 0.27e2 * t39 * t319 * t321 - 0.16e2 / 0.3e1 * t39 * t327 + t628 - 0.16e2 * t630 + 0.8e1 * t633 - 0.8e1 / 0.3e1 * t636 + 0.2e1 / 0.3e1 * t14 * t49 * (0.24e2 * rho[0] * t174 - 0.24e2 * t167) - 0.16e2 / 0.3e1 * t645 - 0.8e2 / 0.27e2 * t649 + 0.16e2 / 0.3e1 * t652 - 0.16e3 / 0.81e2 * t14 * t7 * t656 * t658 + 0.4e2 / 0.9e1 * t325 * t319 * t138 * t144 - 0.4e1 / 0.3e1 * t14 * t137 * t666 - 0.16e2 / 0.9e1 * t325 * t326 * t332 - 0.48e2 * t673 + 0.16e2 * t675 - 0.8e1 * t677 + 0.8e1 / 0.3e1 * t39 * t48 * t332;
  t683 = my_piecewise3(t10, 0, t682);
  t688 = t5 * t337 * t61;
  t691 = t5 * t149 * t157;
  t694 = t5 * t56 * t348;
  t697 = 0.1e1 / t60 / t72;
  t700 = 0.1e2 / 0.27e2 * t5 * t19 * t697;
  t702 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t683 * t20 - t688 / 0.2e1 + t691 / 0.2e1 - 0.5e1 / 0.9e1 * t694 + t700);
  t705 = 0.48e2 * t29 * t174 * t30;
  t707 = t71 * t361 * t75;
  t710 = t172 * t368 * t176;
  t712 = t166 * t166;
  t713 = 0.1e1 / t712;
  t715 = t366 * t713 * t371;
  t720 = 0.1e1 / t712 / t6;
  t723 = 0.1e1 / t74 / t171 / t73;
  t728 = my_piecewise3(t28, 0, t705 + 0.64e2 * t707 - 0.32e2 * t710 + 0.32e3 / 0.27e2 * t715 - 0.16e3 / 0.81e2 * t13 * t365 * rho[1] * t720 * t723);
  t733 = t5 * t376 * t61;
  t736 = t5 * t181 * t157;
  t739 = t5 * t80 * t348;
  t743 = 0.1e2 / 0.27e2 * t5 * t34 * t697;
  t745 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t728 * t20 - t733 / 0.2e1 + t736 / 0.2e1 - 0.5e1 / 0.9e1 * t739 + t743);
  tv4rho40 = 0.4e1 * t353 + 0.4e1 * t390 + t6 * (t702 + t745);

  if(out->v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    out->v4rho4[ip*p->dim.v4rho4 + 0] += tv4rho40;

  t750 = t14 * t406;
  t752 = t14 * t410;
  t757 = t92 * t361 * t48;
  t760 = t92 * t256 * t51;
  t763 = t92 * t409 * t144;
  t772 = -0.48e2 * t750 - 0.16e2 * t752 + 0.8e1 / 0.3e1 * t14 * t417 + 0.4e2 * t757 + 0.16e2 * t760 - 0.4e1 * t763 + 0.4e1 / 0.9e1 * t92 * t202 * t332 + 0.4e1 / 0.3e1 * t619 + t628 - 0.12e2 * t630 + 0.4e1 * t633 - 0.2e1 / 0.3e1 * t636;
  t777 = t92 * t167 * t319 * t138;
  t794 = t437 * t48;
  t798 = -0.4e2 / 0.9e1 * t14 * t414 + 0.2e2 / 0.3e1 * t777 + 0.16e3 / 0.81e2 * t92 * t73 * t656 * t321 - 0.2e2 / 0.9e1 * t92 * t73 * t319 * t51 * t144 - 0.8e1 / 0.3e1 * t645 - 0.2e2 / 0.27e2 * t649 + 0.4e1 / 0.3e1 * t652 - 0.36e2 * t673 + 0.8e1 * t675 - 0.2e1 * t677 + 0.12e2 * t794 + 0.8e1 / 0.3e1 * t219 * t326;
  t800 = my_piecewise3(t10, 0, t772 + t798);
  t805 = t5 * t421 * t61;
  t808 = t5 * t207 * t157;
  t809 = t808 / 0.4e1;
  t811 = t5 * t97 * t348;
  t817 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t800 * t20 - 0.3e1 / 0.8e1 * t805 + t809 - 0.5e1 / 0.36e2 * t811 - t688 / 0.8e1 + t691 / 0.4e1 - 0.5e1 / 0.12e2 * t694 + t700);
  t826 = rho[1] * t174;
  t827 = 0.24e2 * t826;
  t833 = t29 * t76 * t234;
  t834 = 0.4e1 * t833;
  t836 = t71 * t177 * t107;
  t839 = t71 * t449 * t234;
  t843 = t172 * t361 * t371 * t107;
  t846 = t29 * t224 * t466;
  t852 = t29 * t168 * t107;
  t857 = t437 * t30;
  t859 = t440 * t220;
  t862 = t13 * t361 * t441;
  t868 = 0.16e3 / 0.81e2 * t366 * t368 * t723 * t107 + 0.4e1 / 0.3e1 * t71 * t228 * t466 + 0.2e1 / 0.3e1 * t29 * t105 * (-0.6e1 * t167 + t827) + t834 + 0.8e1 * t836 - 0.16e2 / 0.3e1 * t839 - 0.2e2 / 0.3e1 * t843 - 0.2e1 * t846 + 0.2e2 / 0.9e1 * t172 * t456 * t234 + t705 - 0.4e1 * t852 + 0.24e2 * t707 - 0.16e2 / 0.3e1 * t710 + 0.2e2 / 0.27e2 * t715 - 0.12e2 * t857 - 0.12e2 * t859 + 0.4e1 * t862 - 0.2e2 / 0.27e2 * t13 * t368 * t371 * t171;
  t869 = my_piecewise3(t28, 0, t868);
  t874 = t5 * t471 * t61;
  t877 = t5 * t239 * t157;
  t878 = t877 / 0.4e1;
  t880 = t5 * t112 * t348;
  t886 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t869 * t20 - 0.3e1 / 0.8e1 * t874 + t878 - 0.5e1 / 0.36e2 * t880 - t733 / 0.8e1 + t736 / 0.4e1 - 0.5e1 / 0.12e2 * t739 + t743);
  tv4rho41 = t353 + t390 + 0.3e1 * t434 + 0.3e1 * t484 + t6 * (t817 + t886);

  if(out->v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    out->v4rho4[ip*p->dim.v4rho4 + 1] += tv4rho41;

  t895 = t92 * t494;
  t900 = t255 * t368 * t136;
  t904 = t255 * t361 * t319 * t51;
  t925 = -0.8e1 / 0.3e1 * t14 * t256 + 0.4e2 / 0.3e1 * t895 + 0.4e2 / 0.9e1 * t92 * t498 - 0.4e2 / 0.3e1 * t900 - 0.2e3 / 0.27e2 * t904 + 0.2e2 / 0.27e2 * t255 * t497 * t144 - 0.128e3 / 0.3e1 * t750 - 0.64e2 / 0.9e1 * t752 + 0.16e3 / 0.3e1 * t757 + 0.128e3 / 0.9e1 * t760 - 0.16e2 / 0.9e1 * t763 + t628 - 0.8e1 * t630 + 0.4e1 / 0.3e1 * t633 - 0.16e3 / 0.81e2 * t255 * t174 * t656 * t138 + 0.8e2 / 0.27e2 * t777 - 0.8e1 / 0.9e1 * t645 - 0.24e2 * t673 + 0.8e1 / 0.3e1 * t675 + 0.16e2 / 0.3e1 * t794;
  t926 = my_piecewise3(t10, 0, t925);
  t931 = t5 * t502 * t61;
  t934 = t5 * t260 * t157;
  t942 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t926 * t20 - t931 / 0.4e1 + t934 / 0.12e2 - t805 / 0.4e1 + t808 / 0.3e1 - 0.5e1 / 0.18e2 * t811 + t691 / 0.12e2 - 0.5e1 / 0.18e2 * t694 + t700);
  t943 = t29 * t43;
  t944 = t943 * t536;
  t946 = t71 * t73;
  t947 = t371 * t107;
  t956 = t71 * t449 * t278;
  t969 = t437 * t518;
  t971 = t176 * t234;
  t976 = t29 * t228 * t273;
  t978 = t234 * t234;
  t983 = t29 * t76 * t278;
  t990 = t71 * t167 * t371 * t273;
  t992 = 0.16e2 / 0.9e1 * t944 - 0.8e2 / 0.27e2 * t946 * t947 * t234 - 0.8e1 / 0.9e1 * t535 * t517 * t466 - 0.24e2 * t857 - 0.16e2 / 0.9e1 * t956 + 0.8e1 / 0.9e1 * t71 * t228 * t546 + 0.2e2 / 0.27e2 * t172 * t456 * t278 + 0.2e1 / 0.3e1 * t29 * t105 * (-0.12e2 * t167 + t827) - 0.32e2 / 0.9e1 * t969 + 0.16e2 / 0.9e1 * t219 * t971 * rho[1] - 0.8e1 / 0.9e1 * t976 - 0.8e1 / 0.9e1 * t29 * t272 * t978 + 0.4e1 / 0.3e1 * t983 + 0.4e2 / 0.27e2 * t440 * t947 * t70 + 0.8e2 / 0.27e2 * t990;
  t998 = t29 * t224 * t546;
  t1008 = t122 * t521;
  t1013 = t219 * t268;
  t1017 = -0.16e3 / 0.81e2 * t172 * t174 * t723 * t273 - 0.4e1 / 0.3e1 * t998 + 0.16e2 / 0.3e1 * t833 + 0.16e2 / 0.3e1 * t836 - 0.16e2 / 0.9e1 * t839 - 0.4e2 / 0.27e2 * t843 - 0.4e1 / 0.3e1 * t846 - 0.8e1 * t852 - 0.8e1 * t859 + 0.8e1 / 0.9e1 * t862 - 0.8e1 / 0.3e1 * t1008 + 0.4e1 / 0.3e1 * t39 * t75 * t466 + 0.8e1 / 0.3e1 * t1013 + t705 + 0.32e2 / 0.3e1 * t707 - 0.8e1 / 0.9e1 * t710;
  t1019 = my_piecewise3(t28, 0, t992 + t1017);
  t1024 = t5 * t551 * t61;
  t1027 = t5 * t283 * t157;
  t1035 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t1019 * t20 - t1024 / 0.4e1 + t1027 / 0.12e2 - t874 / 0.4e1 + t877 / 0.3e1 - 0.5e1 / 0.18e2 * t880 + t736 / 0.12e2 - 0.5e1 / 0.18e2 * t739 + t743);
  tv4rho42 = 0.2e1 * t434 + 0.2e1 * t484 + 0.2e1 * t512 + 0.2e1 * t561 + t6 * (t942 + t1035);

  if(out->v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    out->v4rho4[ip*p->dim.v4rho4 + 2] += tv4rho42;

  t1051 = t569 * t713 * t319;
  t1057 = -0.12e2 * t673 + t628 - 0.4e1 * t630 - 0.24e2 * t750 + 0.6e2 * t757 + 0.8e1 * t760 + 0.12e2 * t895 - 0.24e2 * t900 - 0.2e2 / 0.3e1 * t904 - 0.8e2 / 0.27e2 * t255 * t570 + 0.14e3 / 0.27e2 * t1051 + 0.16e3 / 0.81e2 * t569 * t368 * t656 * t51;
  t1058 = my_piecewise3(t10, 0, t1057);
  t1063 = t5 * t574 * t61;
  t1070 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t1058 * t20 - t1063 / 0.8e1 - 0.3e1 / 0.8e1 * t931 + t934 / 0.4e1 + t809 - 0.5e1 / 0.12e2 * t811 - 0.5e1 / 0.36e2 * t694 + t700);
  t1071 = t371 * t273;
  t1084 = t943 * t598;
  t1111 = t29 * t43 * t371 * t594;
  t1114 = t29 * t224 * t602;
  t1117 = 0.2e2 / 0.9e1 * t535 * t1071 * t234 - 0.4e1 / 0.3e1 * t535 * t971 * t278 - 0.4e1 / 0.3e1 * t535 * t517 * t546 - 0.2e2 / 0.9e1 * t946 * t947 * t278 + 0.4e1 / 0.3e1 * t1084 + 0.8e1 / 0.3e1 * t944 - 0.36e2 * t857 + 0.4e1 / 0.3e1 * t219 * t176 * t278 * rho[1] + 0.16e3 / 0.81e2 * t71 * t73 * t723 * t594 + 0.2e1 / 0.3e1 * t29 * t105 * (-0.18e2 * t167 + t827) + 0.4e1 / 0.9e1 * t71 * t228 * t602 - 0.8e1 / 0.3e1 * t39 * t536 - 0.2e2 / 0.9e1 * t219 * t1071 * rho[1] - 0.2e2 / 0.27e2 * t1111 - 0.2e1 / 0.3e1 * t1114 - 0.4e1 / 0.3e1 * t956;
  t1128 = t122 * t584;
  t1130 = t122 * t587;
  t1136 = -0.8e1 / 0.3e1 * t969 - 0.8e1 / 0.3e1 * t976 + 0.4e1 * t983 + 0.2e2 / 0.9e1 * t990 - 0.2e1 * t998 + t834 + 0.8e1 / 0.3e1 * t836 - 0.12e2 * t852 + 0.2e1 * t39 * t75 * t546 + 0.4e1 / 0.3e1 * t1128 - 0.2e1 * t1130 - 0.4e1 * t859 - 0.4e1 * t1008 + 0.8e1 * t1013 + t705 + 0.4e1 * t707;
  t1138 = my_piecewise3(t28, 0, t1117 + t1136);
  t1143 = t5 * t607 * t61;
  t1150 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t1138 * t20 - t1143 / 0.8e1 - 0.3e1 / 0.8e1 * t1024 + t1027 / 0.4e1 + t878 - 0.5e1 / 0.12e2 * t880 - 0.5e1 / 0.36e2 * t739 + t743);
  tv4rho43 = 0.3e1 * t512 + 0.3e1 * t561 + t581 + t614 + t6 * (t1070 + t1150);

  if(out->v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    out->v4rho4[ip*p->dim.v4rho4 + 3] += tv4rho43;

  t1164 = my_piecewise3(t10, 0, t628 + 0.64e2 * t757 - 0.32e2 * t900 + 0.32e3 / 0.27e2 * t1051 - 0.16e3 / 0.81e2 * t13 * t568 * rho[0] * t720 * t656);
  t1172 = my_piecewise3(t1, 0, -0.3e1 / 0.8e1 * t5 * t1164 * t20 - t1063 / 0.2e1 + t934 / 0.2e1 - 0.5e1 / 0.9e1 * t811 + t700);
  t1190 = t273 * t273;
  t1197 = t278 * t278;
  t1211 = 0.8e1 / 0.3e1 * t39 * t75 * t602 + 0.8e2 / 0.27e2 * t39 * t371 * t594 - 0.16e2 / 0.3e1 * t39 * t598 + 0.2e1 / 0.3e1 * t29 * t105 * (-0.24e2 * t167 + 0.24e2 * t826) + 0.16e2 / 0.3e1 * t1128 - 0.8e1 * t1130 + 0.16e2 * t1013 + t705 - 0.16e3 / 0.81e2 * t29 * t7 * t723 * t1190 + 0.4e2 / 0.9e1 * t535 * t1071 * t278 - 0.4e1 / 0.3e1 * t29 * t272 * t1197 - 0.16e2 / 0.9e1 * t535 * t517 * t602 - 0.8e2 / 0.27e2 * t1111 - 0.8e1 / 0.3e1 * t1114 - 0.16e2 / 0.3e1 * t976 + 0.8e1 * t983 - 0.16e2 * t852 + 0.16e2 / 0.3e1 * t1084 - 0.48e2 * t857;
  t1212 = my_piecewise3(t28, 0, t1211);
  t1220 = my_piecewise3(t25, 0, -0.3e1 / 0.8e1 * t5 * t1212 * t20 - t1143 / 0.2e1 + t1027 / 0.2e1 - 0.5e1 / 0.9e1 * t880 + t743);
  tv4rho44 = 0.4e1 * t581 + 0.4e1 * t614 + t6 * (t1172 + t1220);

  if(out->v4rho4 != NULL && (p->info->flags & XC_FLAGS_HAVE_LXC))
    out->v4rho4[ip*p->dim.v4rho4 + 4] += tv4rho44;

}

#endif

